default: &default
  adapter: postgresql
  username: rsmm-web
  sslmode: require
  sslkey: <%= ENV["HOME"] + "/.postgresql/rsmm-web.key" %>
  sslcert: <%= ENV["HOME"] + "/.postgresql/rsmm-web.crt" %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rsmm-web-dev

test:
  <<: *default
  database: rsmm-web-test

production:
  <<: *default
  database: rsmm-web

rsmm_db:
  development:
    adapter: postgresql
    host: localhost
    username: rsmm-web
    database: rsmm
  production:
    adapter: postgresql
    host: claudius
    username: rsmm-web
    database: rsmm
    sslmode: require
    sslkey: <%= ENV["HOME"] + "/.postgresql/rsmm-web.key" %>
    sslcert: <%= ENV["HOME"] + "/.postgresql/rsmm-web.crt" %>
