CREATE TABLE IF NOT EXISTS Item(
  item_id INTEGER PRIMARY KEY,
  item_name TEXT NOT NULL,
  ge_limit INTEGER,
  favorite BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS Turn(
  turn_id SERIAL PRIMARY KEY,
  item_id INTEGER NOT NULL REFERENCES Item(item_id) ON UPDATE CASCADE,
  open_ts TIMESTAMP NOT NULL DEFAULT now(),
  close_ts TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Trade(
  turn_id INTEGER REFERENCES Turn(turn_id),
  trade_ts TIMESTAMP NOT NULL DEFAULT now(),
  price INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  PRIMARY KEY(turn_id, trade_ts)
);

CREATE TABLE IF NOT EXISTS Quote(
  quote_ts TIMESTAMP NOT NULL DEFAULT now(),
  item_id INTEGER REFERENCES Item(item_id) ON UPDATE CASCADE,
  bid1 INTEGER NOT NULL,
  ask1 INTEGER NOT NULL,
  synthetic BOOLEAN NOT NULL,
  PRIMARY KEY(item_id, quote_ts)
);

CREATE TABLE IF NOT EXISTS Price(
  item_id INTEGER NOT NULL REFERENCES Item(item_id) ON UPDATE CASCADE,
  day DATE NOT NULL,
  price INTEGER NOT NULL,
  created_ts TIMESTAMP DEFAULT now(),
  PRIMARY KEY(item_id, day)
);